apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zeoe15iul-python 
  janus-idp.io/tekton: zeoe15iul-python
  backstage.io/kubernetes-id: zeoe15iul-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zeoe15iul-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  