apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zeoe15iul-python-gitops
  description: This is GitOps manifest for zeoe15iul-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: zeoe15iul-python
    backstage.io/kubernetes-id: zeoe15iul-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: zeoe15iul-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:zeoe15iul-python
